---
sample_id:
  type: 'String'
  required: true
  help: 'sample id supplied from input yaml'
variant_caller:
  type: 'String'
  required: true
  help: 'Tool used to call structural or somatic variants'
  choices:
    - Mutect2
    - HaplotypeCaller
    - Strelka2
    - Muse2
    - SomaticSniper
    - Delly2
save_intermediate_files:
  type: 'Bool'
  required: true
  default: false
  help: 'Enable to store intermediate files'
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'absolute path to directory to store output'
src_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence (FASTA)'
src_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence index file'
src_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence dictionary'
dest_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence (FASTA)'
dest_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence index file'
dest_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence dictionary'
chain_file:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'FIXME ???'
repeat_bed:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'FIXME ???'
funcotator_data:
  type: 'FuncotatorDataSource'
  required: true
  help: 'Funcotator data source and reference sample IDs'
  elements:
    data_source:
      type: 'Path'
      mode: 'r'
      required: true
      help: 'Root data source folder for Funcotator'
    src_reference_id:
      type: 'String'
      mode: 'r'
      required: true
      help: 'Reference build ID for the source sequence'
    dest_reference_id:
      type: 'String'
      mode: 'r'
      required: true
      help: 'Reference build ID for the destination sequence'
rf_model:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'FIXME ???'
input:
  type: 'Namespace'
  required: true
  help: 'Input sample'
  elements:
    vcf:
      type: 'Path'
      mode: 'r'
      required: true
      help: 'Input dataset supplied by input yaml'
