---
sample_id:
  type: 'String'
  required: true
  help: 'Sample id supplied from input yaml'

liftover_direction:
  type: 'String'
  required: true
  help: 'Direction of LiftOver to perform'
  choices:
    - GRCh37ToGRCh38
    - GRCh38ToGRCh37

variant_caller:
  type: 'String'
  required: true
  help: 'Tool used to call variants'
  choices:
    - Mutect2
    - HaplotypeCaller
    - Strelka2
    - Muse2
    - SomaticSniper
    - Delly2-gSV
    - Delly2-sSV

save_intermediate_files:
  type: 'Bool'
  required: true
  default: false
  help: 'Enable to store intermediate files'

output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Absolute path to directory to store output'

fasta_ref_37:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'GRCh37 FASTA reference'

fasta_ref_38:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'GRCh38 FASTA reference'

src_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence (FASTA)'

src_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence index file'

src_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence dictionary'

dest_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence (FASTA)'

dest_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence index file'

dest_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence dictionary'

chain_file:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Chain file corresponding to LiftOver direction, included in resource-bundle.zip'

rf_model:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to pre-trained random forest model (.Rds) corresponding to variant caller and LiftOver direction'

input:
  type: 'Namespace'
  required: true
  help: 'Input sample'
  elements:
    vcf:
      type: 'Path'
      mode: 'r'
      required: true
      help: 'Input dataset supplied by input yaml'

target_threshold:
  type: 'RangedNumber'
  required: false
  min: 0
  max: 1
  help: >-
    Optional parameter specifying target Stability Score threshold for variant
    filtering Default behavior without `target_threshold` or
    `target_specificity` specified uses threshold maximizing F1-score in whole
    genome validation set'.

target_specificity:
  type: 'RangedNumber'
  required: false
  min: 0
  max: 1
  help: >-
    Optional parameter specifying target specificity for variant filtering
    based on whole genome validation set. Overrides `target_threshold`.
