---
# Required Parameters
output_dir:
  type: 'Path'
  mode: 'w'
  required: true
  help: 'Path to the directory where the output files are to be saved'

variant_caller:
  type: 'String'
  required: true
  help: 'Variant calling algorithm used to generate input VCF'
  choices:
    - HaplotypeCaller
    - Mutect2
    - Strelka2
    - SomaticSniper
    - Muse2
    - Delly2-gSV
    - Delly2-sSV

rf_model:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to corresponding pre-trained random forest model'

liftover_direction:
  type: 'String'
  required: true
  help: 'Conversion direction'
  choices:
    - GRCh37ToGRCh38
    - GRCh38ToGRCh37

fasta_ref_37:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to the GRCh37 reference sequence (FASTA)'

fasta_ref_38:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to the GRCh38 reference sequence (FASTA)'

resource_bundle_path:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to unpacked resource-bundle.zip'

# Optional Parameters
target_threshold:
  type: 'RangedNumber'
  required: false
  min: 0
  max: 1
  default: ''
  help: 'Target Stability Score threshold for variant filtering'

target_specificity:
  type: 'RangedNumber'
  required: false
  min: 0
  max: 1
  default: ''
  help: 'Target specificity based on whole genome validation set for variant filtering'

extract_features_cpus:
  type: 'Integer'
  required: false
  default: 4
  help: 'Number of cpus to use for parallel parsing of large VCFs (>1GB)'

save_intermediate_files:
  type: 'Bool'
  required: false
  default: false
  help: 'If set, save output files from intermediate pipeline processes'

blcds_registered_dataset:
  type: 'Bool'
  required: false
  default: false
  help: 'Set to true when using BLCDS folder structure; use false for now'

ucla_cds:
  type: 'Bool'
  required: false
  default: false
  help: 'If set, overwrite default memory and CPU values by UCLA cluster-specific configs'

# Internal parameters
src_fasta_id:
  type: 'String'
  required: true
  help: 'Source reference genome build identifier'
  choices:
    - GRCh37
    - GRCh38

src_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence (FASTA)'

src_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence index file'

src_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Source reference sequence dictionary'

dest_fasta_id:
  type: 'String'
  required: true
  help: 'Destination reference genome build identifier'
  choices:
    - GRCh37
    - GRCh38

dest_fasta_ref:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence (FASTA)'

dest_fasta_fai:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence index file'

dest_fasta_dict:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Destination reference sequence dictionary'

chain_file:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Chain file for LiftOver conversion'
