---
repeat_bed:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'RepeatMasker (v3.0.1) intervals from UCSC Table Browser for variant annotation in target build coordinates, included in resource-bundle.zip'

funcotator_data_source:
  type: 'Path'
  mode: 'r'
  required: true
  help: 'Path to Funcotator data source directory containing dbSNP, GENCODE and HGNC sources for SNV annotation'
